# Generated by Django 4.2.5 on 2023-09-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_password_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='search',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
