# Generated by Django 4.2.5 on 2023-09-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_password_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='search',
        ),
    ]
