# Generated by Django 4.2.5 on 2023-09-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_password_password_foydalanuvchi_nomi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='foydalanuvchi_nomi',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='password',
            old_name='parol',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='password',
            old_name='veb_sayt',
            new_name='website',
        ),
    ]
