# Generated by Django 4.2.5 on 2023-09-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_foydalanuvchi_nomi_password_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='password',
            new_name='foydalanuvchi_nomi',
        ),
        migrations.RenameField(
            model_name='password',
            old_name='username',
            new_name='parol',
        ),
        migrations.RenameField(
            model_name='password',
            old_name='website',
            new_name='veb_sayt',
        ),
    ]
